parameters:
    netgen_social_connect.base_urls:
        facebook: https://www.facebook.com/app_scoped_user_id/
        #twitter:  https://twitter.com/intent/user?user_id=
        twitter:  https://api.twitter.com/oauth/authenticate?oauth_token=
        google:   https://plus.google.com/
